### PR TITLE
Async versions of ReconfigureTenant, ClearTenants and RemoveTenant

### PR DESCRIPTION
**Pull request by gliljas**
Since we may have reasons to use DisposeAsync, we should have async versions of these methods as well.

I'll gladly add tests, but wonder what style you prefer if there are sync/async versions. Clone the test? Parametrize?

### CODE REVIEW

**Review by tillig — CHANGES_REQUESTED** [review]
Minor doc update and tests needed. I think cloning the associated tests would be better because then we'll get the right name (`MethodName_TestScenario`) and the tests can be explicitly `async Task` instead of sync-over-async or vice-versa. Thanks!

**Comment by gliljas** [comment]
There's a sync Dispose in CreateTenantScope, which could mean that there should be a CreateTenantScopeAsync, but I kind of wonder why it creates a new lifetimeScope and then disposes it immediately if one is already in the dictionary. Of course it should be rare, but I wonder if it's not something that could be solved by the good ol' ConcurrentDictionary of Lazy trick.

```
private ILifetimeScope CreateTenantScope(object tenantId, Action<ContainerBuilder>? configuration = null)
{
    if (_isDisposed == 1)
    {
        throw new ObjectDisposedException(nameof(ApplicationContainer));
    }

    Lazy<ILifetimeScope> lifetimeScope = configuration != null
        ? new Lazy<ILifetimeScope>(() => ApplicationContainer.BeginLifetimeScope(TenantLifetimeScopeTag, configuration))
        : new Lazy<ILifetimeScope>(() => ApplicationContainer.BeginLifetimeScope(TenantLifetimeScopeTag));

    return _tenantLifetimeScopes.GetOrAdd(tenantId, lifetimeScope).Value;
}
```

The dictionary will only ever contain items with resolved values.

**Comment by tillig** [comment]
If you read the comment on the method, the idea was that if, for some reason, the scope couldn't be added to the dictionary due to some sort of limitation, the scope that was just created would be disposed. Like:

1. Create a scope, which sometimes instantiates or calls back to create things.
2. Try to add it to the dictionary.
3. If it wasn't added, dispose of it immediately so the things that may have been created at the time would get cleaned up.

As mentioned in the comment, this should _likely never_ happen.

For now, I'd say let's leave it like it is. It'd be awesome to get the bulk of this PR done and merged in without hanging on this. I'd also say... creating a lifetime scope is a pretty synchronous operation, so I don't know that I'd want to _create_ the scope async or offer a method that makes it _appear_ it's being created async. I'd have to check the code in core Autofac, but I think we end up calling DisposeAsync synchronously in the underlying lifetime scope implementation if plain Dispose is called. Regardless, I'm not sure adding an async create is right, and the rest of this is valuable, so we can maybe address the remainder later.

**Review by tillig — APPROVED** [review]
Awesome, thanks!

**Comment by gliljas** [comment]
I agree that CreateTenantScopeAsync is the wrong way to go. A rare case indeed, so not urgent in any way. 

Thanks for reviewing and merging!

**Pull request merged**
