### PR TITLE
Version increment for the 5.0.1 release.

### PR DESCRIPTION
**Pull request by alistairjevans**

### CODE REVIEW

**Comment by alistairjevans** [comment]
🤦‍♂️

Done

**Comment by alistairjevans** [comment]
Want me to do the release words?

**Comment by tillig** [comment]
Nah, I'm almost done. Draft release pending, just waiting for it to hit NuGet.

**Comment by tillig** [comment]
Done. https://github.com/autofac/Autofac.Multitenant/releases/tag/v5.0.1

**Comment by alistairjevans** [comment]
👍

**Pull request merged**
