### PR TITLE
Fixes issue #19: Invalid interaction between DisposeAsync and Dispose…

### PR DESCRIPTION
**Pull request by me-viper**
Fixes issue #19: Invalid interaction between DisposeAsync and Dispose in MultitenantContainer.

### CODE REVIEW

**Comment by me-viper** [comment]
Made MultitenantContainer.AsyncDispose implantation similar to Container.DisposeAsync implementation.

**Comment by alistairjevans** [comment]
Looks good to me initially; thanks for the contribution @me-viper.

@alsami, can you take a look at this as well?

**Comment by alsami** [comment]
> @alsami, can you take a look at this as well?

Looks fine for me as well! Badly missed on that :)

**Comment by alistairjevans** [comment]
@me-viper, do you have a workaround for this? Or do you get an ObjectDisposedException every time the multi-tenant container is disposed?

**Comment by me-viper** [comment]
> @me-viper, do you have a workaround for this? Or do you get an ObjectDisposedException every time the multi-tenant container is disposed?

Not really. Dispose chain is initiated by IHost on application exit and I can't do much about it. I can probably try to use a wrapper over MultitenantContainer to ensure valid Dispose order but I would really want to avoid that and leave it as a last resort.

**Comment by alistairjevans** [comment]
Ok, thanks. We'll probably do a bug-fix release on this shortly then.

**Comment by alistairjevans** [comment]
@alsami is currently looking at an odd issue in the .NET Core multi-tenant integration; we'll wait and see if there's any impact on the standard multi-tenant integration before we release this one I think.

**Comment by alistairjevans** [comment]
Looks like the two issues were un-related, let's get a 5.0.1 release out. I'll raise a PR with the version change.

**Comment by halllo** [comment]
Maybe also release Autofac.AspNetCore.Multitenant 3.0.2, since it currently still uses Autofac.Multitenant 5.0.0.

**Comment by alsami** [comment]
Thanks for the heads up. For now you can work around that, by additionally referencing the latest version of Autofac.Multitenant.

**Comment by tillig** [comment]
Published v3.0.2 of Autofac.AspNetCore.Multitenant with this fix.

**Pull request merged**
